name: "Update"
on:
  schedule:
    - cron: '19 18 * * *'
  workflow_dispatch:

jobs:
  update-inputs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Nix
      uses: cachix/install-nix-action@v21
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Update Flake Inputs
      run: nix flake update
    - name: Push
      if: ${{ success() }}
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Update Inputs"

  update-metadata:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install Nix
      uses: cachix/install-nix-action@v21
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Install Nu
      uses: hustcer/setup-nu@v3
    - name: Update Mod Metadata
      run: nix run .#update-mod
    - name: Update Resource Metadata
      run: nix run .#update-resource
    - name: Update Shader Metadata
      run: nix run .#update-shader
    - name: Pull
      run: git pull
    - name: Push
      if: ${{ success() }}
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Update Metadata"
      

